name: Api CI/CD

permissions:
  id-token: write

on:
  push:
    paths:
      - 'api/**'
      - 'karthik.Common/**'
      - '.github/workflows/api.yaml'
    branches:
      - main
  pull_request:
    paths:
      - 'api/**'
      - '.github/workflows/api.yaml'
    branches:
      - main

